name: front
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.1.0
  fluttertoast: ^9.0.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  http: ^1.6.0
  google_fonts: ^6.3.0
  flutter_spinkit: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  webview_flutter: ^4.8.0
  flutter_web_auth_2: ^4.1.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/codaez.png

# ğŸ‘‡ must be OUTSIDE "flutter:"
flutter_icons:
  android: true
  ios: true
  image_path: "assets/codaez.png"
